version: '3'
services:
  my-mysql-container:
    image: my-mysql
    container_name: my-mysql-container
    privileged: true
    volumes:
      - ./log:/var/log/mysql
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    ports:
      - '3306:3306'